---

# Copyright 2020-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# override ONOS config
onos-classic:
  config:
    netcfg: >
      {
        "apps" : {
          "org.opencord.igmpproxy": {
            "igmpproxy": {
              "FastLeave": "true",
              "LastQueryInterval": 1,
              "MaxResp": 1,
              "enableIgmpProvisioning": "false",
              "globalConnectPointMode": "true",
              "globalConnectPoint": "of:0000000000000001/3",
              "sourceDeviceAndPort": "of:0000000000000001/3",
              "outgoingIgmpVlanId": 550,
              "outgoingIgmpInnerVlanId": 55,
              "outgoingIgmpWithV3": "true",
              "IgmpCos": 5,
              "IgmpUniCos": 5,
              "PeriodicQuery": "true",
              "KeepAliveInterval": 60,
              "KeepAliveCount": 5,
              "requestDsIgmpPackets": false
            }
          },
          "org.onosproject.core": {
            "multicast": {
              "ingressVlan": 550,
              "egressVlan": 550,
              "egressInnerVlan": 55
            }
          },
          "org.opencord.dhcpl2relay" : {
            "dhcpl2relay" : {
              "useOltUplinkForServerPktInOut" : true
            }
          },
          "org.opencord.kafka": {
            "kafka" : {
              "bootstrapServers" : "{{ .Release.Name }}-kafka.{{ .Release.Namespace }}.svc:9092"
            }
          },
          "org.opencord.sadis": {
            "bandwidthprofile": {
              "integration": {
                "cache": {
                  "enabled": true,
                  "maxsize": 40,
                  "ttl": "PT1m"
                }
              },
              "entries": [
                {
                  "id": "High-Speed-Internet",
                  "cir": 100000,
                  "cbs": 10000,
                  "eir": 100000,
                  "ebs": 10000,
                  "air": 100000
                },
                {
                  "id": "VOIP",
                  "cir": 400000,
                  "cbs": 10000,
                  "eir": 400000,
                  "ebs": 10000,
                  "air": 100000
                },
                {
                  "id": "User1-Specific",
                  "cir": 60000,
                  "cbs": 10000,
                  "eir": 40000,
                  "ebs": 10000
                },
                {
                  "id": "User1-Specific2",
                  "cir": 500000,
                  "cbs": 10000,
                  "eir": 300000,
                  "ebs": 10000
                },
                {
                  "id": "Fixed9Gbps",
                  "cir": 0,
                  "cbs": 0,
                  "eir": 0,
                  "ebs": 0,
                  "air": 9000000
                },
                {
                  "id": "TCONT_TYPE1_200Mbps_Fixed_ForVOIP",
                  "eir": 0,
                  "ebs": 0,
                  "cir": 0,
                  "cbs": 0,
                  "air": 200000
                },
                {
                  "id": "TCONT_TYPE2_500Mbps_Assured_ForVoD",
                  "eir": 0,
                  "ebs": 0,
                  "cir": 500000,
                  "cbs": 10000,
                  "air": 0
                },
                {
                  "id": "TCONT_TYPE3_700Mbps_Peak_500Mbps_Assured_ForVoD",
                  "eir": 200000,
                  "ebs": 10000,
                  "cir": 500000,
                  "cbs": 10000,
                  "air": 0
                },
                {
                  "id": "TCONT_TYPE4_1Gbps_Peak_User1_HSI_Upstream",
                  "eir": 1000000,
                  "ebs": 10000,
                  "cir": 0,
                  "cbs": 0,
                  "air": 0
                },
                {
                  "id": "TCONT_TYPE5_1Gbps_Peak_500Mbps_Assured_200Mbps_Fixed_User1_HSI_Upstream",
                  "eir": 300000,
                  "ebs": 10000,
                  "cir": 500000,
                  "cbs": 10000,
                  "air": 200000
                }
              ]
            },
            "sadis": {
              "integration": {
                "cache": {
                  "enabled": true,
                  "maxsize": 50,
                  "ttl": "PT1m"
                }
              },
              "entries": [
                {
                  "id": "BBSM00000002-1",
                  "nasPortId": "BBSM00000002-1",
                  "circuitId": "BBSM00000002-1",
                  "remoteId": "BBSM00000002-1",
                  "uniTagList": [
                    {
                      "ponCTag": 1,
                      "ponSTag": 7,
                      "technologyProfileId": 64,
                      "downstreamBandwidthProfile": "Fixed9Gbps",
                      "upstreamBandwidthProfile": "Fixed9Gbps",
                      "isDhcpRequired": "false"
                    }
                  ]
                },
                {
                  "id": "BBSM00000001-1",
                  "nasPortId": "BBSM00000001-1",
                  "uniTagList": [
                    {
                      "uniTagMatch": 35,
                      "ponCTag": 1,
                      "ponSTag": 7,
                      "usPonCTagPriority": 0,
                      "usPonSTagPriority": 0,
                      "dsPonCTagPriority": 0,
                      "dsPonSTagPriority": 0,
                      "technologyProfileId": 64,
                      "downstreamBandwidthProfile": "High-Speed-Internet",
                      "upstreamBandwidthProfile": "TCONT_TYPE4_1Gbps_Peak_User1_HSI_Upstream",
                      "isDhcpRequired": "false",
                      "serviceName": "HSIA"
                    },
                    {
                      "uniTagMatch": 65,
                      "ponCTag": 63,
                      "ponSTag": 10,
                      "usPonCTagPriority": 7,
                      "usPonSTagPriority": 7,
                      "dsPonCTagPriority": 7,
                      "dsPonSTagPriority": 7,
                      "technologyProfileId": 65,
                      "downstreamBandwidthProfile": "VOIP",
                      "upstreamBandwidthProfile": "TCONT_TYPE1_200Mbps_Fixed_ForVOIP",
                      "isDhcpRequired": "true",
                      "enableMacLearning": "true",
                      "serviceName": "VOIP"
                    },
                    {
                      "uniTagMatch": 55,
                      "ponCTag": 55,
                      "ponSTag": 555,
                      "usPonCTagPriority": 5,
                      "usPonSTagPriority": 5,
                      "dsPonCTagPriority": 5,
                      "dsPonSTagPriority": 5,
                      "technologyProfileId": 66,
                      "downstreamBandwidthProfile": "High-Speed-Internet",
                      "upstreamBandwidthProfile": "TCONT_TYPE2_500Mbps_Assured_ForVoD",
                      "enableMacLearning": "true",
                      "serviceName": "VOD",
                      "isDhcpRequired": "true",
                      "isIgmpRequired": "true"
                    }
                  ]
                },
                {
                  "id": "BBSM00000003-1",
                  "nasPortId": "BBSM00000003-1",
                  "uniTagList": [
                    {
                      "uniTagMatch": 35,
                      "ponCTag": 1,
                      "ponSTag": 7,
                      "usPonCTagPriority": 0,
                      "usPonSTagPriority": 0,
                      "dsPonCTagPriority": 0,
                      "dsPonSTagPriority": 0,
                      "technologyProfileId": 65,
                      "downstreamBandwidthProfile": "High-Speed-Internet",
                      "upstreamBandwidthProfile": "TCONT_TYPE5_1Gbps_Peak_500Mbps_Assured_200Mbps_Fixed_User1_HSI_Upstream",
                      "isDhcpRequired": "true",
                      "serviceName": "HSIA"
                    },
                    {
                      "uniTagMatch": 65,
                      "ponCTag": 63,
                      "ponSTag": 10,
                      "usPonCTagPriority": 7,
                      "usPonSTagPriority": 7,
                      "dsPonCTagPriority": 7,
                      "dsPonSTagPriority": 7,
                      "technologyProfileId": 65,
                      "downstreamBandwidthProfile": "VOIP",
                      "upstreamBandwidthProfile": "TCONT_TYPE1_200Mbps_Fixed_ForVOIP",
                      "isDhcpRequired": "true",
                      "enableMacLearning": "true",
                      "serviceName": "VOIP"
                    },
                    {
                      "uniTagMatch": 55,
                      "ponCTag": 55,
                      "ponSTag": 555,
                      "usPonCTagPriority": 5,
                      "usPonSTagPriority": 5,
                      "dsPonCTagPriority": 5,
                      "dsPonSTagPriority": 5,
                      "technologyProfileId": 67,
                      "downstreamBandwidthProfile": "High-Speed-Internet",
                      "upstreamBandwidthProfile": "TCONT_TYPE3_700Mbps_Peak_500Mbps_Assured_ForVoD",
                      "enableMacLearning": "true",
                      "serviceName": "VOD",
                      "isDhcpRequired": "true",
                      "isIgmpRequired": "true"
                    },
                    {
                      "ponCTag": 55,
                      "ponSTag": 550,
                      "dsPonCTagPriority": 5,
                      "dsPonSTagPriority": 5,
                      "technologyProfileId": 67,
                      "serviceName": "MC"
                    }
                  ]
                },
                {
                  "id": "BBSIM_OLT_0",
                  "hardwareIdentifier": "0a:0a:0a:0a:0a:00",
                  "ipAddress": "127.0.0.1",
                  "uplinkPort": "1048576"
                },
                {
                  "id": "BBSIM_OLT_1",
                  "hardwareIdentifier": "0a:0a:0a:0a:0a:00",
                  "ipAddress": "127.0.0.1",
                  "uplinkPort": "1048576"
                }
              ]
            }
          }
        }
      }
    componentConfig:
      "org.opencord.olt.impl.OltFlowService": >
        {
          "enableDhcpOnNni": "true",
          "defaultTechProfileId": "64",
          "enableIgmpOnNni": "true",
          "enableEapol": "false",
          "enableDhcpV6": "false",
          "enableDhcpV4": "true"
        }

# override BBSim config
servicesConfig:
  workflow: tt
  services:
    - name: hsia
      uni_tag_match: 35
      c_tag: 900
      c_tag_allocation: unique
      s_tag: 900
      s_tag_allocation: shared
      tp_id: 64
    - name: voip
      uni_tag_match: 65
      c_tag: 63
      c_tag_allocation: shared
      s_tag: 10
      s_tag_allocation: shared
      needs_dhcp: true
      tp_id: 65
      configure_mac_address: true
      us_pon_c_tag_priority: 7
      us_pon_s_tag_priority: 7
      ds_pon_c_tag_priority: 7
      ds_pon_s_tag_priority: 7
    - name: vod
      uni_tag_match: 55
      c_tag: 55
      c_tag_allocation: shared
      s_tag: 555
      s_tag_allocation: shared
      needs_dhcp: true
      needs_igmp: true
      tp_id: 66
      configure_mac_address: true
      us_pon_c_tag_priority: 5
      us_pon_s_tag_priority: 5
      ds_pon_c_tag_priority: 5
      ds_pon_s_tag_priority: 5
    # NOTE: the multicast service must be called MC unless you set
    # multicastServiceName to something else in org.opencord.olt.impl.Olt
    - name: MC
      c_tag: 55
      c_tag_allocation: shared
      s_tag: 550
      s_tag_allocation: shared
      tp_id: 66
      ds_pon_c_tag_priority: 5
      ds_pon_s_tag_priority: 5
